parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    env(DATABASE_PASS_FILE): '/run/secrets/db_dba_password'     
    #database_pass: '%env(file:DATABASE_PASS_FILE)%'
    env(DB_URL): 'mysql://web:%env(file:DATABASE_PASS_FILE)%@db:3306/web'
    #env(DB_URL): 'mysql://web:%database_pass%@sql:$

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        # With Symfony 3.3, remove the `resolve:` prefix
        #url: '%env(resolve:DATABASE_URL)%'
        url: 'mysql://web:%env(trim:file:DATABASE_PASS_FILE)%@db:3306/web'
        
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
